name: Haskell CI Build an Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Haskell cabal Build GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10.7']
        cabal: ['3.6.2.0']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: cabal configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct --write-ghc-environment-files=always

    - name: cabal freeze
      run: cabal freeze

    - name: Cache cabal store
      uses: actions/cache@v3
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: cabal build --only-dependencies
      run: |
        cabal update
        cabal build --only-dependencies
        
    - name: cabal build
      run: cabal build
      
    - name: cabal test
      run: cabal test all
      
    - name: Set up HLint
      uses: haskell/actions/hlint-setup@v2
      with:
        version: '3.1.6'
        
    - name: Run HLint
      uses: haskell/actions/hlint-run@v2
      with:
        path: '["src/", "test/", "app/"]'
        fail-on: warning
